addos:
  - linux
  - osx

language : node_js

node_js :
 - stable

branches:
  only:
  - master

install:
 - npm ci

before_script:
# db setup - https://docs.travis-ci.com/user/database-setup/#mongodb 
  - sleep 15
  - sudo mongod
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run test:osx          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run test:lin        ; fi

  